# Generated by Django 2.2.5 on 2020-01-25 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eprofile_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='profile',
        ),
    ]
